function hstx_geometry2dtool(){var T='',Bb='" for "gwt:onLoadErrorFn"',zb='" for "gwt:onPropertyErrorFn"',mb='"><\/script>',bb='#',Hb='&',ec='.cache.html',db='/',pb='//',$b='516B587E804B0CB60A02269D40FCEF07',ac='5B34F208C1BA204A60FD888B979C908A',dc=':',_b=':1',tb='::',gc='<script defer="defer">hstx_geometry2dtool.onInjectionDone(\'hstx_geometry2dtool\')<\/script>',lb='<script id="',wb='=',cb='?',yb='Bad handler "',bc='CDADF058C4702BA8705A1617107447EC',cc='D29A7F66ABD2D4B6058E45698B0C799D',fc='DOMContentLoaded',nb='SCRIPT',kb='__gwt_marker_hstx_geometry2dtool',ob='base',gb='baseUrl',X='begin',W='bootstrap',fb='clear.cache.gif',vb='content',Mb='desktop',ab='end',Gb='formfactor',Ub='gecko',Vb='gecko1_8',Y='gwt.codesvr=',Z='gwt.hosted=',$='gwt.hybrid',Ab='gwt:onLoadErrorFn',xb='gwt:onPropertyErrorFn',ub='gwt:property',Yb='hosted.html?hstx_geometry2dtool',U='hstx_geometry2dtool',ib='hstx_geometry2dtool.nocache.js',sb='hstx_geometry2dtool::',Rb='ie10',Tb='ie8',Sb='ie9',Cb='iframe',eb='img',Lb='ios',Kb='ipad',Ib='iphone',Jb='ipod',Db="javascript:''",Xb='loadExternalRefs',qb='meta',Fb='moduleRequested',_='moduleStartup',Qb='msie',rb='name',Eb='position:absolute;width:0;height:0;border:none',Pb='safari',hb='script',Zb='selectingPermutation',V='startup',jb='undefined',Wb='unknown',Nb='user.agent',Ob='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=T,u={},v=[],w=[],A=[],B=0,C,D;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:X});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function F(){var b=false;try{var c=m.location.search;return (c.indexOf(Y)!=-1||(c.indexOf(Z)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf($)==-1}catch(a){}F=function(){return b};return b}
function G(){if(q&&r){var b=n.getElementById(U);var c=b.contentWindow;if(F()){c.__gwt_getProperty=function(a){return L(a)}}hstx_geometry2dtool=null;c.gwtOnLoad(C,U,t,B);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:ab})}}
function H(){function e(a){var b=a.lastIndexOf(bb);if(b==-1){b=a.length}var c=a.indexOf(cb);if(c==-1){c=a.length}var d=a.lastIndexOf(db,Math.min(c,b));return d>=0?a.substring(0,d+1):T}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(eb);b.src=a+fb;a=e(b.src)}return a}
function g(){var a=J(gb);if(a!=null){return a}return T}
function h(){var a=n.getElementsByTagName(hb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(ib)!=-1){return e(a[b].src)}}return T}
function i(){var a;if(typeof isBodyLoaded==jb||!isBodyLoaded()){var b=kb;var c;n.write(lb+b+mb);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=nb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return T}
function j(){var a=n.getElementsByTagName(ob);if(a.length>0){return a[a.length-1].href}return T}
function k(){var a=n.location;return a.href==a.protocol+pb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==T){l=h()}if(l==T){l=i()}if(l==T){l=j()}if(l==T&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function I(){var b=document.getElementsByTagName(qb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(rb),g;if(f){f=f.replace(sb,T);if(f.indexOf(tb)>=0){continue}if(f==ub){g=e.getAttribute(vb);if(g){var h,i=g.indexOf(wb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=T}u[f]=h}}else if(f==xb){g=e.getAttribute(vb);if(g){try{D=eval(g)}catch(a){alert(yb+g+zb)}}}else if(f==Ab){g=e.getAttribute(vb);if(g){try{C=eval(g)}catch(a){alert(yb+g+Bb)}}}}}}
function J(a){var b=u[a];return b==null?null:b}
function K(a,b){var c=A;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function L(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(D){D(a,d,b)}throw null}
var M;function N(){if(!M){M=true;var a=n.createElement(Cb);a.src=Db;a.id=U;a.style.cssText=Eb;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:_,millis:(new Date).getTime(),type:Fb});a.contentWindow.location.replace(t+P)}}
w[Gb]=function(){var a=location.search;var b=a.indexOf(Gb);if(b>=0){var c=a.substring(b);var d=c.indexOf(wb)+1;var e=c.indexOf(Hb);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Ib)!=-1||(f.indexOf(Jb)!=-1||f.indexOf(Kb)!=-1)){return Lb}return Mb};v[Gb]={desktop:0,ios:1};w[Nb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Ob)!=-1}())return Pb;if(function(){return b.indexOf(Qb)!=-1&&n.documentMode>=10}())return Rb;if(function(){return b.indexOf(Qb)!=-1&&n.documentMode>=9}())return Sb;if(function(){return b.indexOf(Qb)!=-1&&n.documentMode>=8}())return Tb;if(function(){return b.indexOf(Ub)!=-1}())return Vb;return Wb};v[Nb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};hstx_geometry2dtool.onScriptLoad=function(){if(M){r=true;G()}};hstx_geometry2dtool.onInjectionDone=function(){q=true;o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:Xb,millis:(new Date).getTime(),type:ab});G()};I();H();var O;var P;if(F()){if(m.external&&(m.external.initModule&&m.external.initModule(U))){m.location.reload();return}P=Yb;O=T}o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:Zb});if(!F()){try{K([Mb,Vb],$b);K([Lb,Vb],$b);K([Mb,Vb],$b+_b);K([Lb,Vb],$b+_b);K([Mb,Rb],ac);K([Lb,Rb],ac);K([Mb,Rb],ac+_b);K([Lb,Rb],ac+_b);K([Mb,Sb],bc);K([Lb,Sb],bc);K([Mb,Sb],bc+_b);K([Lb,Sb],bc+_b);K([Mb,Pb],cc);K([Lb,Pb],cc);K([Mb,Pb],cc+_b);K([Lb,Pb],cc+_b);O=A[L(Gb)][L(Nb)];var Q=O.indexOf(dc);if(Q!=-1){B=Number(O.substring(Q+1));O=O.substring(0,Q)}P=O+ec}catch(a){return}}var R;function S(){if(!s){s=true;G();if(n.removeEventListener){n.removeEventListener(fc,S,false)}if(R){clearInterval(R)}}}
if(n.addEventListener){n.addEventListener(fc,function(){N();S()},false)}var R=setInterval(function(){if(/loaded|complete/.test(n.readyState)){N();S()}},50);o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:W,millis:(new Date).getTime(),type:ab});o&&o({moduleName:U,sessionId:p,subSystem:V,evtGroup:Xb,millis:(new Date).getTime(),type:X});n.write(gc)}
hstx_geometry2dtool();