function digitscoordinategrapher(){var bb='',$=' top: -1000px;',yb='" for "gwt:onLoadErrorFn"',wb='" for "gwt:onPropertyErrorFn"',hb='");',zb='#',Jb='&',fc='.cache.js',Bb='/',Hb='//',_b='56895B5150E59ABD7197935B5FC390F4',bc='80698DE1254011A640CFBA9C549CD138',ec=':',ac=':1',qb='::',mc=':moduleBase',ab='<!doctype html>',cb='<html><head><\/head><body><\/body><\/html>',tb='=',Ab='?',cc='A2DF3EE97F369F714E5AA2D9158ED49A',vb='Bad handler "',_='CSS1Compat',fb='Chrome',eb='DOMContentLoaded',V='DUMMY',dc='E9864F280E95D40276E64D1644E0989B',lc='Ignoring non-whitelisted Dev Mode URL: ',kc='__gwtDevModeHook:digitscoordinategrapher',Gb='base',Eb='baseUrl',Q='begin',W='body',P='bootstrap',Db='clear.cache.gif',sb='content',Ob='desktop',T='digitscoordinategrapher',$b='digitscoordinategrapher.devmode.js',Fb='digitscoordinategrapher.nocache.js',pb='digitscoordinategrapher::',hc='end',gb='eval("',jc='file:',Ib='formfactor',Wb='gecko',Xb='gecko1_8',R='gwt.codesvr.digitscoordinategrapher=',S='gwt.codesvr=',xb='gwt:onLoadErrorFn',ub='gwt:onPropertyErrorFn',rb='gwt:property',mb='head',ic='http:',Tb='ie10',Vb='ie8',Ub='ie9',X='iframe',Cb='img',Nb='ios',Mb='ipad',Kb='iphone',Lb='ipod',jb='javascript',Y='javascript:""',gc='loadExternalRefs',nb='meta',lb='moduleRequested',kb='moduleStartup',Sb='msie',ob='name',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',Rb='safari',ib='script',Zb='selectingPermutation',U='startup',db='undefined',Yb='unknown',Pb='user.agent',Qb='webkit';var o=window;var p=document;r(P,Q);function q(){var a=o.location.search;return a.indexOf(R)!=-1||a.indexOf(S)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:T,sessionId:o.__gwtStatsSessionId,subSystem:U,evtGroup:a,millis:(new Date).getTime(),type:b})}}
digitscoordinategrapher.__sendStats=r;digitscoordinategrapher.__moduleName=T;digitscoordinategrapher.__errFn=null;digitscoordinategrapher.__moduleBase=V;digitscoordinategrapher.__softPermutationId=0;digitscoordinategrapher.__computePropValue=null;digitscoordinategrapher.__getPropMap=null;digitscoordinategrapher.__gwtInstallCode=function(){};digitscoordinategrapher.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[T]={moduleName:T};var v;function w(){B();return v}
function A(){B();return v.getElementsByTagName(W)[0]}
function B(){if(v){return}var a=p.createElement(X);a.src=Y;a.id=T;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==_?ab:bb;v.write(b+cb);v.close()}
function C(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=w();var g;if(navigator.userAgent.indexOf(fb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(gb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(hb));g=f.createElement(ib);g.language=jb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(ib);g.language=jb;g.text=c[i];e.appendChild(g);d(e,g)}}}
digitscoordinategrapher.onScriptDownloaded=function(a){l(function(){m(a)})};r(kb,lb);var n=p.createElement(ib);n.src=k;p.getElementsByTagName(mb)[0].appendChild(n)}
digitscoordinategrapher.__startLoadingFragment=function(a){return G(a)};digitscoordinategrapher.__installRunAsyncCode=function(a){var b=A();var c=w().createElement(ib);c.language=jb;c.text=a;b.appendChild(c);b.removeChild(c)};function D(){var c={};var d;var e;var f=p.getElementsByTagName(nb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(ob),k;if(j){j=j.replace(pb,bb);if(j.indexOf(qb)>=0){continue}if(j==rb){k=i.getAttribute(sb);if(k){var l,m=k.indexOf(tb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=bb}c[j]=l}}else if(j==ub){k=i.getAttribute(sb);if(k){try{d=eval(k)}catch(a){alert(vb+k+wb)}}}else if(j==xb){k=i.getAttribute(sb);if(k){try{e=eval(k)}catch(a){alert(vb+k+yb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;digitscoordinategrapher.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(zb);if(b==-1){b=a.length}var c=a.indexOf(Ab);if(c==-1){c=a.length}var d=a.lastIndexOf(Bb,Math.min(c,b));return d>=0?a.substring(0,d+1):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Cb);b.src=a+Db;a=e(b.src)}return a}
function g(){var a=t(Eb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(ib);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Fb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Gb);if(a.length>0){return a[a.length-1].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Hb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return digitscoordinategrapher.__moduleBase+a}
function H(){var g=[];var h;function i(a,b){var c=g;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var j=[];var k=[];function l(a){var b=k[a](),c=j[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
k[Ib]=function(){var a=location.search;var b=a.indexOf(Ib);if(b>=0){var c=a.substring(b);var d=c.indexOf(tb)+1;var e=c.indexOf(Jb);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Kb)!=-1||(f.indexOf(Lb)!=-1||f.indexOf(Mb)!=-1)){return Nb}return Ob};j[Ib]={desktop:0,ios:1};k[Pb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Qb)!=-1}())return Rb;if(function(){return b.indexOf(Sb)!=-1&&p.documentMode>=10}())return Tb;if(function(){return b.indexOf(Sb)!=-1&&p.documentMode>=9}())return Ub;if(function(){return b.indexOf(Sb)!=-1&&p.documentMode>=8}())return Vb;if(function(){return b.indexOf(Wb)!=-1}())return Xb;return Yb};j[Pb]={gecko1_8:0,ie10:1,ie8:2,ie9:3,safari:4};s=function(a,b){return b in j[a]};digitscoordinategrapher.__getPropMap=function(){var a={};for(var b in j){if(j.hasOwnProperty(b)){a[b]=l(b)}}return a};digitscoordinategrapher.__computePropValue=l;o.__gwt_activeModules[T].bindings=digitscoordinategrapher.__getPropMap;r(P,Zb);if(q()){return G($b)}var m;try{i([Ob,Rb],_b);i([Nb,Rb],_b);i([Ob,Rb],_b+ac);i([Nb,Rb],_b+ac);i([Ob,Xb],bc);i([Nb,Xb],bc);i([Ob,Xb],bc+ac);i([Nb,Xb],bc+ac);i([Ob,Ub],cc);i([Nb,Ub],cc);i([Ob,Ub],cc+ac);i([Nb,Ub],cc+ac);i([Ob,Tb],dc);i([Nb,Tb],dc);i([Ob,Tb],dc+ac);i([Nb,Tb],dc+ac);m=g[l(Ib)][l(Pb)];var n=m.indexOf(ec);if(n!=-1){h=parseInt(m.substring(n+1),10);m=m.substring(0,n)}}catch(a){}digitscoordinategrapher.__softPermutationId=h;return G(m+fc)}
function I(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(gc,Q);r(gc,hc)}
D();digitscoordinategrapher.__moduleBase=F();u[T].moduleBase=digitscoordinategrapher.__moduleBase;var J=H();if(o){var K=!!(o.location.protocol==ic||o.location.protocol==jc);o.__gwt_activeModules[T].canRedirect=K;if(K){var L=kc;var M=o.sessionStorage[L];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(M)){if(M&&(window.console&&console.log)){console.log(lc+M)}M=bb}if(M&&!o[L]){o[L]=true;o[L+mc]=F();var N=p.createElement(ib);N.src=M;var O=p.getElementsByTagName(mb)[0];O.insertBefore(N,O.firstElementChild||O.children[0]);return false}}}I();r(P,hc);C(J);return true}
digitscoordinategrapher.succeeded=digitscoordinategrapher();