function digitsintegerchips(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Db='&',bc='.cache.html',_='/',lb='//',Xb='1A38F11B42A3260EE10770958BED9F40',ac=':',Yb=':1',pb='::',dc='<script defer="defer">digitsintegerchips.onInjectionDone(\'digitsintegerchips\')<\/script>',hb='<script id="',sb='=',$='?',Zb='AE36BC786F0DAE35660CB5AE027ADFBE',ub='Bad handler "',$b='C74D5A32017B817C5EBAC632140D7FFC',cc='DOMContentLoaded',_b='F04A9209B2E369A250DBA3FECBAF1F43',jb='SCRIPT',gb='__gwt_marker_digitsintegerchips',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',rb='content',Ib='desktop',Q='digitsintegerchips',eb='digitsintegerchips.nocache.js',ob='digitsintegerchips::',Y='end',Cb='formfactor',Rb='gecko',Sb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',Vb='hosted.html?digitsintegerchips',Qb='ie6',Pb='ie8',Ob='ie9',yb='iframe',ab='img',Hb='ios',Gb='ipad',Eb='iphone',Fb='ipod',zb="javascript:''",Ub='loadExternalRefs',mb='meta',Bb='moduleRequested',X='moduleStartup',Nb='msie',nb='name',Kb='opera',Ab='position:absolute;width:0;height:0;border:none',Mb='safari',db='script',Wb='selectingPermutation',R='startup',fb='undefined',Tb='unknown',Jb='user.agent',Lb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}digitsintegerchips=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){var a=location.search;var b=a.indexOf(Cb);if(b>=0){var c=a.substring(b);var d=c.indexOf(sb)+1;var e=c.indexOf(Db);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Eb)!=-1||(f.indexOf(Fb)!=-1||f.indexOf(Gb)!=-1)){return Hb}return Ib};v[Cb]={desktop:0,ios:1};w[Jb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Kb)!=-1}())return Kb;if(function(){return b.indexOf(Lb)!=-1}())return Mb;if(function(){return b.indexOf(Nb)!=-1&&n.documentMode>=9}())return Ob;if(function(){return b.indexOf(Nb)!=-1&&n.documentMode>=8}())return Pb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Qb;if(function(){return b.indexOf(Rb)!=-1}())return Sb;return Tb};v[Jb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};digitsintegerchips.onScriptLoad=function(){if(I){r=true;C()}};digitsintegerchips.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Ub,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=Vb;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Wb});if(!B()){try{G([Ib,Sb],Xb);G([Hb,Sb],Xb);G([Ib,Sb],Xb+Yb);G([Hb,Sb],Xb+Yb);G([Ib,Mb],Zb);G([Hb,Mb],Zb);G([Ib,Mb],Zb+Yb);G([Hb,Mb],Zb+Yb);G([Ib,Ob],$b);G([Hb,Ob],$b);G([Ib,Ob],$b+Yb);G([Hb,Ob],$b+Yb);G([Ib,Kb],_b);G([Hb,Kb],_b);G([Ib,Kb],_b+Yb);G([Hb,Kb],_b+Yb);K=x[H(Cb)][H(Jb)];var M=K.indexOf(ac);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+bc}catch(a){return}}var N;function O(){if(!s){s=true;C();if(n.removeEventListener){n.removeEventListener(cc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(cc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Ub,millis:(new Date).getTime(),type:T});n.write(dc)}
digitsintegerchips();