function envisiondataandgraphs(){var W='',T=' top: -1000px;',rb='" for "gwt:onLoadErrorFn"',pb='" for "gwt:onPropertyErrorFn"',ab='");',sb='#',Cb='&',ic='.cache.js',ub='/',Ab='//',ac='16B8351E4FFE608D426A03E17DB0174E',cc='1E834ECCA257506421717FA48B34B7D7',dc='66DC0A6464F023BEAB55FB9B4BEF0A19',ec='7B00A39A58043C8AB4BF554EA771AFB1',hc=':',bc=':1',jb='::',V='<!doctype html>',X='<html><head><\/head><body><\/body><\/html>',mb='=',tb='?',fc='BDDDFB5BBC0BA97BB6BD7664DC60DA09',ob='Bad handler "',gc='C03EC9C2D196B95FF2DBA7D3DCF3E00B',U='CSS1Compat',$='Chrome',Z='DOMContentLoaded',O='DUMMY',Nb='Unexpected exception in locale detection, using default: ',Mb='_',Lb='__gwt_Locale',zb='base',xb='baseUrl',J='begin',P='body',I='bootstrap',wb='clear.cache.gif',lb='content',Jb='default',Hb='desktop',kc='end',M='envisiondataandgraphs',$b='envisiondataandgraphs.devmode.js',yb='envisiondataandgraphs.nocache.js',ib='envisiondataandgraphs::',_b='es_US',_='eval("',Bb='formfactor',Wb='gecko',Xb='gecko1_8',K='gwt.codesvr.envisiondataandgraphs=',L='gwt.codesvr=',qb='gwt:onLoadErrorFn',nb='gwt:onPropertyErrorFn',kb='gwt:property',fb='head',Vb='ie6',Ub='ie8',Tb='ie9',Q='iframe',vb='img',Gb='ios',Fb='ipad',Db='iphone',Eb='ipod',cb='javascript',R='javascript:""',jc='loadExternalRefs',Ib='locale',Kb='locale=',gb='meta',eb='moduleRequested',db='moduleStartup',Sb='msie',hb='name',Pb='opera',S='position:absolute; width:0; height:0; border:none; left: -1000px;',Rb='safari',bb='script',Zb='selectingPermutation',N='startup',Y='undefined',Yb='unknown',Ob='user.agent',Qb='webkit';var q=window;var r=document;t(I,J);function s(){var a=q.location.search;return a.indexOf(K)!=-1||a.indexOf(L)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:M,sessionId:q.__gwtStatsSessionId,subSystem:N,evtGroup:a,millis:(new Date).getTime(),type:b})}}
envisiondataandgraphs.__sendStats=t;envisiondataandgraphs.__moduleName=M;envisiondataandgraphs.__errFn=null;envisiondataandgraphs.__moduleBase=O;envisiondataandgraphs.__softPermutationId=0;envisiondataandgraphs.__computePropValue=null;envisiondataandgraphs.__getPropMap=null;envisiondataandgraphs.__gwtInstallCode=function(){};envisiondataandgraphs.__gwtStartLoadingFragment=function(){return null};var u=function(){return false};var v=function(){return null};__propertyErrorFunction=null;var w=q.__gwt_activeModules=q.__gwt_activeModules||{};w[M]={moduleName:M};var x;function y(){A();return x}
function z(){A();return x.getElementsByTagName(P)[0]}
function A(){if(x){return}var a=r.createElement(Q);a.src=R;a.id=M;a.style.cssText=S+T;a.tabIndex=-1;r.body.appendChild(a);x=a.contentDocument;if(!x){x=a.contentWindow.document}x.open();var b=document.compatMode==U?V:W;x.write(b+X);x.close()}
function B(k){function l(a){function b(){if(typeof r.readyState==Y){return typeof r.body!=Y&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(Z,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(Z,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=z();var f=y();var g;if(navigator.userAgent.indexOf($)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(_));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(ab));g=f.createElement(bb);g.language=cb;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(bb);g.language=cb;g.text=c[i];e.appendChild(g);d(e,g)}}}
envisiondataandgraphs.onScriptDownloaded=function(a){l(function(){m(a)})};t(db,eb);var n=r.createElement(bb);n.src=k;r.getElementsByTagName(fb)[0].appendChild(n)}
envisiondataandgraphs.__startLoadingFragment=function(a){return E(a)};envisiondataandgraphs.__installRunAsyncCode=function(a){var b=z();var c=y().createElement(bb);c.language=cb;c.text=a;b.appendChild(c);b.removeChild(c)};function C(){var c={};var d;var e;var f=r.getElementsByTagName(gb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(hb),k;if(j){j=j.replace(ib,W);if(j.indexOf(jb)>=0){continue}if(j==kb){k=i.getAttribute(lb);if(k){var l,m=k.indexOf(mb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=W}c[j]=l}}else if(j==nb){k=i.getAttribute(lb);if(k){try{d=eval(k)}catch(a){alert(ob+k+pb)}}}else if(j==qb){k=i.getAttribute(lb);if(k){try{e=eval(k)}catch(a){alert(ob+k+rb)}}}}}v=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;envisiondataandgraphs.__errFn=e}
function D(){function e(a){var b=a.lastIndexOf(sb);if(b==-1){b=a.length}var c=a.indexOf(tb);if(c==-1){c=a.length}var d=a.lastIndexOf(ub,Math.min(c,b));return d>=0?a.substring(0,d+1):W}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(vb);b.src=a+wb;a=e(b.src)}return a}
function g(){var a=v(xb);if(a!=null){return a}return W}
function h(){var a=r.getElementsByTagName(bb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(yb)!=-1){return e(a[b].src)}}return W}
function i(){var a=r.getElementsByTagName(zb);if(a.length>0){return a[a.length-1].href}return W}
function j(){var a=r.location;return a.href==a.protocol+Ab+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==W){k=h()}if(k==W){k=i()}if(k==W&&j()){k=e(r.location.href)}k=f(k);return k}
function E(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return envisiondataandgraphs.__moduleBase+a}
function F(){var i=[];var j;function k(a,b){var c=i;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
m[Bb]=function(){var a=location.search;var b=a.indexOf(Bb);if(b>=0){var c=a.substring(b);var d=c.indexOf(mb)+1;var e=c.indexOf(Cb);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Db)!=-1||(f.indexOf(Eb)!=-1||f.indexOf(Fb)!=-1)){return Gb}return Hb};l[Bb]={desktop:0,ios:1};m[Ib]=function(){var b=null;var c=Jb;try{if(!b){var d=location.search;var e=d.indexOf(Kb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Cb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=v(Ib)}if(!b){b=q[Lb]}if(b){c=b}while(b&&!u(Ib,b)){var h=b.lastIndexOf(Mb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Nb+a)}q[Lb]=c;return b||Jb};l[Ib]={'default':0,es_US:1};m[Ob]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Pb)!=-1}())return Pb;if(function(){return b.indexOf(Qb)!=-1}())return Rb;if(function(){return b.indexOf(Sb)!=-1&&r.documentMode>=9}())return Tb;if(function(){return b.indexOf(Sb)!=-1&&r.documentMode>=8}())return Ub;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Vb;if(function(){return b.indexOf(Wb)!=-1}())return Xb;return Yb};l[Ob]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};u=function(a,b){return b in l[a]};envisiondataandgraphs.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};envisiondataandgraphs.__computePropValue=n;q.__gwt_activeModules[M].bindings=envisiondataandgraphs.__getPropMap;t(I,Zb);if(s()){return E($b)}var o;try{k([Hb,_b,Tb],ac);k([Gb,_b,Tb],ac);k([Hb,_b,Tb],ac+bc);k([Gb,_b,Tb],ac+bc);k([Hb,Jb,Tb],cc);k([Gb,Jb,Tb],cc);k([Hb,Jb,Tb],cc+bc);k([Gb,Jb,Tb],cc+bc);k([Hb,_b,Xb],dc);k([Gb,_b,Xb],dc);k([Hb,_b,Xb],dc+bc);k([Gb,_b,Xb],dc+bc);k([Hb,Jb,Rb],ec);k([Gb,Jb,Rb],ec);k([Hb,Jb,Rb],ec+bc);k([Gb,Jb,Rb],ec+bc);k([Hb,_b,Rb],fc);k([Gb,_b,Rb],fc);k([Hb,_b,Rb],fc+bc);k([Gb,_b,Rb],fc+bc);k([Hb,Jb,Xb],gc);k([Gb,Jb,Xb],gc);k([Hb,Jb,Xb],gc+bc);k([Gb,Jb,Xb],gc+bc);o=i[n(Bb)][n(Ib)][n(Ob)];var p=o.indexOf(hc);if(p!=-1){j=parseInt(o.substring(p+1),10);o=o.substring(0,p)}}catch(a){}envisiondataandgraphs.__softPermutationId=j;return E(o+ic)}
function G(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}t(jc,J);t(jc,kc)}
C();envisiondataandgraphs.__moduleBase=D();w[M].moduleBase=envisiondataandgraphs.__moduleBase;var H=F();G();t(I,kc);B(H);return true}
envisiondataandgraphs.succeeded=envisiondataandgraphs();